config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  devise_for :users
  resources :books, only: [ :create, :index, :show, :destroy, :edit , :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  patch 'books/:id' => 'books#create'
  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  validates :title, presence: true
  validates :body, presence: true
  validates :title, length: {maximum: 200}
  validates :body, length: {maximum: 200}

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment ,  presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  #都道府県コードから都道府県名に自動で変換する。
  include JpPrefecture
  jp_prefecture :prefecture_code
  
  #~.prefecture_nameで都道府県名を参照出来る様にする。
  #例) @user.prefecture_nameで該当ユーザーの住所(都道府県)を表示出来る。

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  
  def address
    address_city+address_street
  end
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  attachment :profile_image

  validates :name, length: {maximum: 20}
  validates :name, length: {minimum: 2}
  validates :name, uniqueness: true
  validates :introduction, length: {maximum: 50}
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top , :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)

    user_path(resource)
  end

  def after_sign_out_path_for(resource)

    root_path
  end

  def after_sign_up_path_for(resource)

     user_path(resource)
  end


  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[
        :email,
        :postcode,
        :prefecture_name,
        :prefecture_code,
        :address_city,
        :address_street
      ])
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book=Book.find(params[:book_id])
    comment = BookComment.new(book_commnt_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_commnt_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]


  def create
    @user=current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
        flash[:notice] = 'successfully'
        redirect_to book_path(@book)
    else
        @books = Book.all
        render :index
    end
  end

  def index
  @user = current_user
  @book = Book.new
  @books = Book.all
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end

  end

  def destroy
    book =Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end





end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


 def index
  @user = current_user
  @book =Book.new
  @users = User.all
  #ログインしている人の投稿を載せない方法を下記のように考えた
  #@users = User.where.not(name: @user.name)
 end

 def show
     @user = User.find(params[:id])
     @user_books = @user.books
     @book = Book.new
 end

 def edit
   @user = User.find(params[:id])
   if @user == current_user
     render "edit"
   else
     redirect_to user_path(current_user)
   end

 end

 def update
   @user = User.find(params[:id])

   if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user)
   else
    render :edit
   end
 end

 private

 def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div  class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h1>Editing Book</h1>
<%= form_with model:@book,local:true do |f| %>
<div class="form-group">
  <label>Title</label>
  <%= f.text_field :title %>
</div>

<div class="form-group">
  <label>Opinon</label>
  <%= f.text_area :body %>
</div>


  <%= f.submit 'Update Book ' , class: "btn btn-success" %>
<% end %>

<%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
    </div>

  </div>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
  <h1>User info</h1>
 <div class="profile-container">
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

  <table class="table">
   <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= @user.name %></th>
    </tr>
    <tr>
     <th>introduction</th>
     <th><%= @user.introduction %></th>
    </tr>
   </tbody>
  </table>
  <div class="row">
     <%= link_to "", edit_user_path(@user.id) , class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>
</div>


<h2 class="mt-3">New book</h2>


<%= form_with model: @book, local:true do |f| %>
 <div class ="form-group">
     <%= f.label:title %>
     <%= f.text_field:title, class: 'form-control book_title' %>
 </div>

 <div class ="form-group">
      <%= f.label :opinion %>
      <%= f.text_field:body, class: 'form-control book_title' %><br>
 <div class="form-group">
   <%= f.submit 'Create Book' , class: "btn btn-success" %>
 </div>
  <% end %>
 </div>
</div>



<div class="col-md-8 offset-md-1">
 <h2>Books</h2>
 <table class="table table-hover table-inverse">
  <tr>
   <th></th>
   <th>Title</th>
   <th>Opinion</th>
   <th colspan="3"></th>
  </tr>

 <% @books.each do |book| %>
 <tr>
  <td>
   <%= link_to user_path(book.user) do %>
   <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
   <% end %>
   </td>
  <td><%= link_to book.title , book_path(book)  %></td>
  <td><%= book.body %></td>
          <% if book.favorited_by?(current_user) %>
                  <td>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                     <%= book.favorites.count %>
                     <i class="fa fa-heart text-red" aria-hidden="true"></i>
                    <% end %>
                  </td>
                     <% else %>

                  <td>
                    <%= link_to book_favorites_path(book), method: :post do %>
                     <%= book.favorites.count %>
                     <i class="fa fa-heart text-blue" aria-hidden="true" style="color: blue;"></i>
                    <% end %>
                  </td>
                <% end %>

  <td><%= link_to "#{book.book_comments.count} コメント" ,  book_path(book) %></td>


 </tr>
<% end %>

</table>
 </div>
</div>


</div>

app/views/books/show.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <h1>User info</h1>
          <div class="profile-container">
              <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
              <table class="table">
                <tbody>
                    <tr></tr>
                    <tr>
                       <th>name</th>
                      <th><%= @book.user.name %></th>
                    </tr>
                    <tr>
                      <th>introduction</th>
                      <th><%= @book.user.introduction %></th>
                    </tr>
                </tbody>
              </table>

                      <div class="row">
                        <%= link_to "", edit_user_path(@book.user.id) , class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
                      </div>


                      <h2 class="mt-3">New book</h2>


                      <%= form_with model: @book_new, local:true do |f| %>
                          <div class ="form-group">
                             <%= f.label:title %>
                             <%= f.text_field:title, class: 'form-control book_title' %>
                         </div>

                             <div class ="form-group">
                                  <%= f.label :opinion %>
                                  <%= f.text_field:body, class: 'form-control book_title' %><br>
                                 <div class="form-group">
                                   <%= f.submit 'Create Book' , class: "btn btn-success" %>
                                 </div>
                        <% end %>
                 </div>
            </div>
          </div>



    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <table class="table">
           <tbody>
              <tr>
                <td> <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
                      <%= link_to @book.user.name , user_path(@book.user.id) %>
                </td>

                <td><%= @book.title%></td>
                <td><%= @book.body %></td>

                <% if @book.user==current_user %>
                <td><%= link_to "Edit", edit_book_path(@book.id) , class: "btn btn-sm btn-success" %></button> </td>
                <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？"  , class: "btn btn-sm btn-danger" %></a></td>

                <% else %>
                <td></td>
                <td></td>

                <% end %>

              <% if @book.favorited_by?(current_user) %>
                  <td>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                     <%= @book.favorites.count %>
                     <i class="fa fa-heart text-red" aria-hidden="true"></i>
                    <% end %>
                  </td>

                   <% else %>

                  <td>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                     <%= @book.favorites.count %>
                     <i class="fa fa-heart text-blue" aria-hidden="true"></i>
                    <% end %>
                  </td>
              <% end %>

                <td>
                   コメント件数 : <%= @book.book_comments.count %>
                </td>


              </tr>
          </tbody>
        </table>

        <div>
          <% @book.book_comments.each do |book_comment| %>
           <p><%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></p>
              <%= book_comment.user.name %>
              <%= book_comment.created_at.strftime('%Y/%m/%d') %>
              <%= book_comment.comment %>
              <% if book_comment.user == current_user %>

                  <%= link_to "Destroy" , book_book_comment_path(book_comment.book, book_comment), method: :delete , class: "btn btn-sm btn-danger" %>
                  <% end %>

              <% end %>
        </div>

        <div>
          <%= form_with(model: [@book,@book_comment], local: true) do |f| %>
           <%= f.text_area :comment, rows: '5' ,placeholder: "コメントをここに"  %>
           <%= f.submit "送信する" %>
          <% end %>
        </div>
</div>

app/views/homes/about.html.erb
<% if flash[:notice] %>
 <p><%= flash[:notice] %></p>
 <% end %>


<!DOCTYPE html>
<html><head>
    <title>Bookers2Ver2</title>
    <meta name="csrf-param" content="authenticity_token">
<meta name="csrf-token" content="SNW67lw0j0hj7aFDEkK8m3ULadk1/c/J3A3kcRIJV2ABpU5brteJBwlWvdAHxwOp4QHHWT9HIx5a1U5r6ebh0g==">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" media="all" href="/assets/application-16605eadccf37c23d1fa922dd614f45b9f2cf25723e2e4032f1975b02ea7d11f.css" data-turbolinks-track="reload">
    <script src="/assets/application-3ac47b8571e58aab844e8d0a988f0f55d8a16c1a75953470343f79cf1bec8528.js" data-turbolinks-track="reload"></script>
  </head>
  <body>
      <main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>



</body></html>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in" , new_user_session_path , class: "btn btn-info btn-sm btn-block mb-3 sign_in"  %>
          </div>
          <div class="row">
            <%= link_to "Sign up" , new_user_registration_path , class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
         <%= link_to "Bookers", root_path , class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li><%= link_to "Home" , user_path(current_user.id) , class: "fas fa-home nav-link text-light" %></li>
              <li> <%= link_to "Users" ,users_path , class: "fas fa-users nav-link text-light"%> </li>
              <li> <%= link_to "Books" ,books_path , class: "fas fa-book-open nav-link text-light" %> </li>
              <li> <%= link_to"logout" , destroy_user_session_path, method: :delete , class: "fas fa-sign-out-alt nav-link text-light" %></li>
              <% else %>
              <li><%= link_to "Home" , root_path , class: "fas fa-home nav-link text-light" %> </li>
              <li><%= link_to "About" , home_about_path, class: "fas fa-link nav-link text-light" %></li>
              <li><%= link_to "sign up" ,new_user_registration_path , class: "fas fa-user-plus nav-link text-light" %> </li>
              <li><%= link_to "login" , new_user_session_path , class: "fas fa-sign-in-alt nav-link text-light" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
    <%- flash.each do |key, value|  %>
    <%= content_tag(:div, value, class: "flash flash__#{key}") %>
    <% end %>
        <%= yield %>
    </div>
    <footer>
      <div class="container mt-5">
        <div class="row">
    	   <div class="mx-auto">
        CopyRight Infratop.inc
        </div>
        </div
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h2>Userinfo</h2>
        <%= form_with model:@user, local:true do |f| %>

<div class="form-group">
  <%= f.label:name %>
  <%= f.text_field :name, class: 'form-control'%>
</div>

<div class="form-group">
  <label for="inputImage">image</label><br>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
</div>

<div class="form-group">
 <%= f.label :introduction %>
 <%= f.text_field :introduction, class: "form-control"%>
</div>

<div class="form-group">
      <%= f.submit "Update User" , class: "btn-secondary" %>
    </button>
</div>
<% end %>
</div>
    </div>

</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
 <h1>User info</h1>
 <div class="profile-container">

  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
   <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= @user.name %></th>
    </tr>

    <tr>
     <th>introduction</th>
     <th><%= @user.introduction %></th>
    </tr>
   </tbody>
  </table>

  <div class="row">
   <%= link_to "",edit_user_path(@user.id) , class: "btn btn-outline-secondary btn-block fas fa-user-cog " %>
  </div>
  </div>





  <h2 class="mt-3">New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model: @book, local:true do |f| %>
 <div class ="form-group">
     <%= f.label:title %>
     <%= f.text_field:title, class: 'form-control book_title' %>
 </div>

 <div class ="form-group">
      <%= f.label :opinion %>
      <%= f.text_field:body, class: 'form-control book_title' %><br>
 <div class="form-group">
   <%= f.submit 'Create Book' , class: "btn btn-success" %>
 </div>
  <% end %>
 </div>
</div>



  <div class="col-md-8 offset-md-1">
    <h1>Users</h1>
  <table class="table">
   <tr>
    <th>image</th>
    <th>name</th>
   </tr>
   <% @users.each do |user| %>
   <tr>
    <td> <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
    <td><%= user.name %></td>
    <td><%= link_to "Show", user_path(user.id) %> </td>
   </tr>
   <% end %>
  </table>
</div>

app/views/users/show.html.erb
<div class="px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
             <h1>User info</h1>
<div class="profile-container">
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
      <tbody>
          <tr></tr>
          <tr>
              <th>name</th>
              <th><%= @user.name %></th>
          </tr>
          <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
          </tr>
      </tbody>
  </table>

  <div class="row">

     <%= link_to "", edit_user_path(@user.id) , class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>

  </div>
</div>


     <h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model:@book, local:true do |f| %>
 <div class ="form-group">
     <%= f.label:title %>
     <%= f.text_field:title, class: 'form-control book_title' %>
 </div>

 <div class ="form-group">
      <%= f.label :opinion %>
      <%= f.text_field:body, class: 'form-control book_title' %><br>
 <div class="form-group">
   <%= f.submit 'Create Book' , class: "btn btn-success" %>
 </div>
  <% end %>
 </div>
</div>


<div class="col-md-8 offset-md-1">
    <h2>Books</h2>
   <table class="table table-hover table-inverse">
      <tr>
          <th>Title</th>
          <th>Opinon</th>
      </tr>
      <% @user_books.each do |book| %>
      <tr>
          <td><%= link_to user_path(@user) do %>
              <%= attachment_image_tag book.user , :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
              <% end %>
         </td>
          <td><%=link_to book.title , book_path(book) %></td>
          <td><%= book.body %></td>
           <% if book.favorited_by?(current_user) %>
                  <td>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                     <%= book.favorites.count %>
                     <i class="fa fa-heart text-red " aria-hidden="true"></i>
                    <% end %>
                  </td>

                   <% else %>

                  <td>
                    <%= link_to book_favorites_path(book), method: :post do %>
                     <%= book.favorites.count %>
                     <i class="fa fa-heart text-blue" aria-hidden="true"></i>
                    <% end %>
                  </td>
              <% end %>
               <td>
                   コメント件数 : <%= book.book_comments.count %>
                </td>

      </tr>
      <% end %>
  </table>
</div>
 </div>
</div>

<script type ="text/javascript">
    function initMap() {
        
        var test = {lat: <%= @user.latitude %>, lng: <%= @user.longitube %>};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: test
            });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);
        
        var contentString = '住所 : <%= @user.address %>';
        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });
        
        var marker = new google.maps.Marker({
                        postition: test,
                        map: map,
                        title: contentString
                        });
                        
        marker.addListener('click', function(){
            infowindow.open(map, marker);
        });
    }
</script>

<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>

<style type ="text/css">
    #map {
        height: 200px;
        width: 70%;
    }
</style>

<div id ="map"></div>